import {
  SiReact,
  SiVuedotjs,
  SiJavascript,
  SiHtml5,
  SiCss,
  SiTailwindcss,
  SiVite,
  SiFlutter,
  SiDart,
  SiC,
  SiCplusplus,
  SiPython,
  SiNodedotjs,
  SiExpress,
  SiFastapi,
  SiPostgresql,
  SiMysql,
  SiDocker,
  SiGit,
  SiLinux,
  SiVercel,
  SiSqlalchemy,
  SiNginx,
} from 'react-icons/si'
import {
  Smartphone,
  Network,
  Mail,
  Database,
  GitBranch,
  Cable,
  Router,
} from 'lucide-react'

export const SKILL_ICONS = {
  React: { icon: SiReact, color: '#61DAFB' },
  'Vue.js': { icon: SiVuedotjs, color: '#4FC08D' },
  JavaScript: { icon: SiJavascript, color: '#F7DF1E' },
  'HTML5': { icon: SiHtml5, color: '#E34F26' },
  'CSS3': { icon: SiCss, color: '#1572B6' },
  'Tailwind CSS': { icon: SiTailwindcss, color: '#06B6D4' },
  Vite: { icon: SiVite, color: '#646CFF' },
  Flutter: { icon: SiFlutter, color: '#02569B' },
  Dart: { icon: SiDart, color: '#0175C2' },
  'Responsive Design': { icon: Smartphone, color: '#64748B' },

  C: { icon: SiC, color: '#A8B9CC' },
  'C++': { icon: SiCplusplus, color: '#00599C' },
  Python: { icon: SiPython, color: '#3776AB' },
  'Node.js': { icon: SiNodedotjs, color: '#5FA04E' },
  'Express.js': { icon: SiExpress, color: '#71717A' },
  FastAPI: { icon: SiFastapi, color: '#009688' },
  SQLAlchemy: { icon: SiSqlalchemy, color: '#D71F00' },
  'REST APIs': { icon: Network, color: '#64748B' },
  Nodemailer: { icon: Mail, color: '#64748B' },

  PostgreSQL: { icon: SiPostgresql, color: '#4169E1' },
  MySQL: { icon: SiMysql, color: '#4479A1' },
  'Queries SQL': { icon: Database, color: '#64748B' },
  'Design relacional': { icon: GitBranch, color: '#64748B' },

  Docker: { icon: SiDocker, color: '#2496ED' },
  'Git/GitHub': { icon: SiGit, color: '#F05032' },
  Linux: { icon: SiLinux, color: '#FCC624' },
  FTTH: { icon: Cable, color: '#64748B' },
  Roteamento: { icon: Router, color: '#64748B' },
  Nginx: { icon: SiNginx, color: '#009639' },
  Vercel: { icon: SiVercel, color: '#71717A' },
}

export const getSkillIcon = (name) => SKILL_ICONS[name] ?? { icon: Network, color: '#64748B' }
